#POSTGRES CREDENTIALS
export POSTGRESQL_USERNAME=udagrambenyoucefdev
export POSTGRESQL_PASSWORD=udagrambenyoucefdev
export POSTGRESQL_DATABASE=udagrambenyoucefdev
export POSTGRESQL_HOST=udagrambenyoucefdev.czwozcrqmqkz.us-east-1.rds.amazonaws.com
export POSTGRESQL_AWS_REGION=us-east-1
export POSTGRESQL_AWS_PROFILE=default
export POSTGRESQL_AWS_MEDIA_BUCKET=udagram-benyoucef-dev
